name = "globalenergyduty"
main = "src/index.js"
compatibility_date = "2026-04-28"

[[d1_databases]]
binding = "DB"
database_name = "energy-duty-db"
database_id = "918134bf-e4ea-4b46-aa24-68abf9f1ddde"
